name: CI

on:
  push:
    branches-ignore:
      - ''

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        version:
          - '1.3'
        os:
          - ubuntu-latest
        arch:
          - x64

    steps:
      - name: Checkout InvertibleNetworks.jl
        uses: actions/checkout@v2

      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Build InvertibleNetworks.jl
        uses: julia-actions/julia-buildpkg@latest

      - name: Run tests
        uses: julia-actions/julia-runtest@latest

      - name: Run simple example
        if: runner.os == 'linux'
        run: julia --project examples/layers/layer_actnorm.jl

